In [ ]:
list =[1,2,3,4,5]
print(list)

[1, 2, 3, 4, 5]


In [ ]:
A= ["Deon",2,3,4,5, list,"ile"]
print(A)

['Deon', 2, 3, 4, 5, [1, 2, 3, 4, 5], 'ile']


In [ ]:
!pip install numpy

In [ ]:
import numpy as np
Np1 = np.array([1,2,3,4,5,6,7])
print(Np1)

[1 2 3 4 5 6 7]


In [ ]:
print(Np1.shape) # to print the dimensions

(7,)


In [ ]:
Np2 =np.arange(10)
print( "Np2 =", Np2)

# OR
Np3 = np.arange(1,10,2)
print("Np3=", Np3)

Np2 = [0 1 2 3 4 5 6 7 8 9]
Np3= [1 3 5 7 9]


In [ ]:
# using the zeros function to create zeros
Zeros = np.zeros(10)
print(Zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Two dimensional arrays

In [ ]:
Np4= np.zeros((2,10)) # this is a 2 dimensional array of zeros
print(Np4)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
Np5  = np.full((10),6) #printing 6s
print(Np5)

# two dimensions of 6s
Np6= np.full((2,10), 6)
print(Np6)

[6 6 6 6 6 6 6 6 6 6]
[[6 6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6 6]]


In [ ]:
# Converting python List to Numpy array
MyList=[1,2,3,4]

Np7 =np.array(MyList)
print(Np7)

[1 2 3 4]


Slicing Numpy Arrays

In [ ]:

import numpy as np
Np8 = np.array([1,2,3,4,5,6,7,8,9])

# to slice ,2,3,4,7
print(Np8[1],Np8[2], Np8[3], Np8[6])

Np9 = np.array([Np8[1],Np8[2]])
print(Np9)

2 3 4 7
[2 3]


In [ ]:
#Another way to slice numpu array
Np10 = np.array([1,2,3,4,5,6,7,8,9])
# to slice from 2 to 5
print(Np10[1:5])

[2 3 4 5]


In [ ]:
# print from 4 - 9
print(Np10[3:])

[4 5 6 7 8 9]


In [ ]:
# To print from the end backawards ( fro 7- 8 donwards)
print(Np10[-3:-1])

# to print 5 to 9 downward
print(Np10[-5:])

# 1 to 5
print(Np10[:5])

[7 8]
[5 6 7 8 9]
[1 2 3 4 5]


In [ ]:
# Slicing with steps

print(Np10[1:6:2]) # this prints from 2 to 6 in steps of 2

[2 4 6]


In [ ]:
#printing from start to end in steps 2
print(Np10[::2])
print(Np10[::])

[1 3 5 7 9]
[1 2 3 4 5 6 7 8 9]


In [ ]:
# Slicing 2 dimensional array
Np11 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(Np11)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
# printing out a single item from 2d array
print(Np11[1,2])

8


In [ ]:
# slicing a 2d array

print(Np11[::, -3])

[3 8]


Copy vs View