In [2]:
!pip install numpy

In [4]:
!pip install numpy
import numpy as np
np.__version__

'1.25.2'

**Array Initialization - single dimension**

In [5]:
import numpy as np
a =np.array([7,9,9,2])
print(a)

[7 9 9 2]


Array Initialization - multi dimension

In [9]:
import numpy as np
a =np.array([(7,9,9,2),(16,11,9,6),(3,4,5,3)]) # this is a three dimentional array
print(a)

[[ 7  9  9  2]
 [16 11  9  6]
 [ 3  4  5  3]]


**Generating** **Array**

In [12]:
c= np.arange(10) #range of values in array
d= np.linspace(1,5,10) #set of values by interval [start,end,no.ofvaluesEqualInterval]
print(c)
print(d)

[0 1 2 3 4 5 6 7 8 9]
[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


Array properties

In [14]:
a = np.array([7,9,9,2])
b = np.array([(7,9,9,2),(16,11,9,6)])
print(a.ndim) #shows Dimension of array
print(a.itemsize) #shows the byte size of each element
print(a.dtype)   #show data type of array
print(a.size*a.itemsize)   #shows memory occuppoed i.e space occuppiedd by 1 element * length of numpy array
print(b.size) # shows number of elements in array
print(b.shape) #shows shape of array(rows and columns)



1
8
int64
32
8
(2, 4)


**Array Reshaping**

In [17]:
b = np.array([(7,9,9,2),(16,11,9,6)])
print(b)
b=b.reshape(4,2)
print(b)

[[ 7  9  9  2]
 [16 11  9  6]]
[[ 7  9]
 [ 9  2]
 [16 11]
 [ 9  6]]


**Array Slicing**

In [26]:
b = np.array([(7,9,9,2),(16,11,9,6)])
print(b[0,2]) # slicing the element from certain row and certain column b[rowIndex,ElementIndex]
print(b[0:,3]) #slcing element from all rows and certain collumn

9
[9 9]


**Array Value operation**

In [27]:
b = np.array([(7,9,9,2,16,11,9,6)])
print(b.min())  #minimum value in Array
print(b.max())  #maximum value in Array
print(b.sum()) #Sum of Array

2
16
69


**Array Arithmetic Operation**

In [34]:
a = np.array([7,9,9,2])
b = np.array([1,9,9,6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[ 8 18 18  8]
[ 6  0  0 -4]
[ 7 81 81 12]
[7.         1.         1.         0.33333333]


In [29]:
 a = np.array([7,9,9,2])
 b = np.array([(7,9,9,2,16,11,9,6)])
 print(b.sum(axis=0))   #sums each elememtn of 1st dimention array with the same index with another dimention
 print(b.sum(axis=1))   #sums of all elements in 1st dimention & sum of all elements in 2nd dimention
 print(np.sqrt(a)) #finds square root of each element
 print(np.std(a))  #finds standard diviation of the array
 print(np.exp(a))  #finds exponential of the array
 print(np.log(a))  # natural log of array -In
 print(np.log10(a)) #log base 10

[ 7  9  9  2 16 11  9  6]
[69]
[2.64575131 3.         3.         1.41421356]
2.8613807855648994
[1.09663316e+03 8.10308393e+03 8.10308393e+03 7.38905610e+00]
[1.94591015 2.19722458 2.19722458 0.69314718]
[0.84509804 0.95424251 0.95424251 0.30103   ]


In [30]:
 a = np.array([(7,9,9,2),(16,11,9,6)])
 b = np.array([(1,2,3,4),(5,6,7,8)])
 print(np.vstack((a,b)))  # vertical stacking of arrays
 print(np.hstack((a,b)))  #Horizontal stack
 print(a.ravel()) #merges dimenntions in array into a single dimention

[[ 7  9  9  2]
 [16 11  9  6]
 [ 1  2  3  4]
 [ 5  6  7  8]]
[[ 7  9  9  2  1  2  3  4]
 [16 11  9  6  5  6  7  8]]
[ 7  9  9  2 16 11  9  6]
