In [2]:

# to create 1-D array and get shape
import numpy as np
Np1=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(Np1)
print(Np1.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


In [4]:
Np2=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(Np2)
print(Np2.shape)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
(2, 6)


In [6]:
#reshape
#2-D
Np3=Np1.reshape(3,4)
print(Np3)
print(Np3.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [7]:
#3-D
Np4=Np1.reshape(2,3,2)
print(Np4)
print(Np4.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)


In [8]:
#reverting a reshape

Np5=Np4.reshape(-1)
print(Np5)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
