In [13]:
import numpy as np

Np1= np.array([1,2,3,4,5,6,7,8,9])
print(Np1)

[1 2 3 4 5 6 7 8 9]


In [3]:
#To find the square root of each element
print(np.sqrt(Np1))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.        ]


In [6]:
# to find the absolute value of each element
Np2= np.array([-3,-2,-1,0,1,2,3,4,5,6,7,8,9])
print(Np2)

#absolute value
print(np.absolute(Np2))

[-3 -2 -1  0  1  2  3  4  5  6  7  8  9]
[3 2 1 0 1 2 3 4 5 6 7 8 9]


In [8]:
# exponent fn

print(np.exp(Np1))

[4.97870684e-02 1.35335283e-01 3.67879441e-01 1.00000000e+00
 2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03]


In [14]:
# Minimum fn

print(np.min(Np1))

1


In [20]:
# maximum function
print(np.max(Np1))

9


In [23]:
# sin function
print(np.cos(Np1))

[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003 -0.91113026]


In [22]:
# sign function

print(np.sign(Np2))

[-1 -1 -1  0  1  1  1  1  1  1  1  1  1]
